---
title: "Scientific talks"
description: |
  <p align="center"><i class="fas fa-chalkboard-teacher fa-7x"></i></p>
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Hierarchical correction

* [Math For Genomics](talks/hierarchicalcorrection_lamme/ "Hierarchical FDR correction") (30 minutes)

<aside>
June 3, 2020 <br>
LaMME, Évry
</aside>

# About the choice of the tree in metagenomics differential abundance studies

* [Séminaire MIAT](talks/impactoftreechoice_miat/ "Impact of tree choice in metagenomics differential abundance studies") (1 hour)

<aside>
Septembre 13, 2019 <br>
INRA, Toulouse
</aside>

* [useR!](posters/user19/index.html "Quantifying the impact of tree choice in metagenomics differential abundance studies with R") (Poster - Winner of BIM's poster prize)

<aside>
July 11, 2019 <br>
Toulouse
</aside>

* [Journées de Statistique](talks/impactoftreechoice_jds/ "Impact of tree choice in metagenomics differential abundance studies") (20 minutes)

<aside>
June 6, 2019 <br>
Nancy
</aside>

* [Groupe de Travail des Thésards de Jussieu](talks/impactoftreechoice_gttjussieu/ "Impact of tree choice in metagenomics differential abundance studies") (1 hour)

<aside>
March 25, 2019 <br>
Sorbonne Université, Paris
</aside>

* [Séminaire StatInfOmics](talks/impactoftreechoice_statinfomics/ "Impact of tree choice in metagenomics differential abundance studies") (1 hour)

<aside>
March 11, 2019 <br>
INRA, Jouy-en-Josas
</aside>

* [Statistical Methods for Post Genomic Data](talks/impactoftreechoice_smpgd/ "Impact of tree choice in metagenomics differential abundance studies") (15 minutes)

<aside>
January 31, 2019
Barcelona
</aside>

* [Séminaire AgroParisTech](talks/impactoftreechoice_agro/impactoftreechoice_agro.html "Impact of tree choice in metagenomics differential abundance studies") (1 hour)

<aside>
January 14, 2019
AgroParisTech, Paris
</aside>